backend:
  name: github
  repo: candoruk96/maliq.github.io
  branch: main

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "pages"
    label: "Sayfalar"
    files:
      - label: "Ana Sayfa"
        name: "index"
        file: "index.html"
        fields:
          - { name: "title", label: "Sayfa Başlığı", widget: "string" }
          - { name: "content", label: "İçerik", widget: "markdown" }
