backend:
  name: git-gateway
  branch: main

media_folder: "assets/images" 
public_folder: "/assets/images"

collections:
  - name: "recipes"
    label: "Tarifler"
    folder: "_data/recipes"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Yemek Adı", widget: "string" }
      - { name: "emoji", label: "Emoji", widget: "string", required: false }
      - { name: "category", label: "Kategori", widget: "string" }
      - label: "Malzemeler"
        name: "ingredients"
        widget: "list"
        fields:
          - { name: "name", label: "Ad", widget: "string" }
          - { name: "qty", label: "Miktar", widget: "string" }
          - { name: "unit", label: "Birim", widget: "string" }
      - { name: "instructions", label: "Tarif Metni", widget: "markdown" }
