backend:
  name: github
  repo: candoruk96/candoruk96.github.io
  branch: main
  auth:
    client_id: "Ov23liC9jwIFXPXz3jcH"
  auth_endpoint: "https://maliq-oauth.vercel.app/auth"

backend:
  name: github
  repo: candoruk96/candoruk96.github.io
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "recipes"
    label: "Tarifler"
    folder: "_data/recipes"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Yemek Adı", widget: "string" }
      - { name: "emoji", label: "Emoji", widget: "string", required: false }
      - { name: "category", label: "Kategori", widget: "string" }
      - label: "Malzemeler"
        name: "ingredients"
        widget: "list"
        fields:
          - { name: "name", label: "Ad", widget: "string" }
          - { name: "qty", label: "Miktar", widget: "string" }
          - { name: "unit", label: "Birim", widget: "string" }
      - { name: "instructions", label: "Tarif Metni", widget: "markdown" }
